from tkinter import *
window=Tk()
window.title("Age calculator")
window.geometry("400x400")
frame=Frame(master=window,bg="blue")
l1=Label(frame,text="enter your name")
e1=Entry(frame)
l2=Label(frame,text="enter your birthdate ")
e2=Entry(frame)
l3=Label(frame,text="enter the name of the month when you were born")
e3=Entry(frame)
l4=Label(frame,text="enter your birthyear")
e4=Entry(frame)
def calculateAge():
    name=e1.get()
    date=e2.get()
    month=e3.get()
    year=int(e4.get())
    age=2025-year
    message=f"your name is {name}. You were born on {date}/{month}/{year}.Your age is {age}"
    text.insert(END,message)
text=Text(frame,height=3)
button=Button(frame,text="Calculate Age",bg="orange",command=calculateAge)
frame.pack()
l1.pack()
e1.pack()
l2.pack()
e2.pack()
l3.pack()
e3.pack()
l4.pack()
e4.pack()
text.pack()
button.pack()
window.mainloop()
